# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.
# This workflow will download a prebuilt DotNet version, install dependencies and run integration tests

name: Run Integration Tests

on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  integration_test:
    name: Build and Run Integration Tests on Dotnet ${{ matrix.dotnet-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet-version: ['2.1.x']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install Dotnet dependencies
      run: |
        echo -e "\n\033[0;35mCommand: dotnet restore"
        dotnet restore
        echo -e "\n\033[0;35mCommand: dotnet build --no-restore"
        dotnet build --no-restore

    - name: Execute Dotnet integration tests
      # continue-on-error: true
      env:
        LANGUAGE_TRANSLATOR_APIKEY: ${{ secrets.LT_APIKEY }}
        LANGUAGE_TRANSLATOR_URL: "https://api.us-south.language-translator.watson.cloud.ibm.com"
        NATURAL_LANGUAGE_UNDERSTANDING_APIKEY: ${{ secrets.NLU_APIKEY }}
        NATURAL_LANGUAGE_UNDERSTANDING_URL: "https://api.us-south.natural-language-understanding.watson.cloud.ibm.com"
        SPEECH_TO_TEXT_APIKEY: ${{ secrets.STT_APIKEY }}
        SPEECH_TO_TEXT_URL: "https://api.us-south.speech-to-text.watson.cloud.ibm.com"
        TEXT_TO_SPEECH_APIKEY: ${{ secrets.TTS_APIKEY }}
        TEXT_TO_SPEECH_URL: "https://api.us-south.text-to-speech.watson.cloud.ibm.com"
        ASSISTANT_APIKEY: ${{ secrets.WA_APIKEY }}
        ASSISTANT_WORKSPACE_ID: ${{ secrets.WA_WORKSPACE_ID }}
        ASSISTANT_ASSISTANT_ID: ${{ secrets.WA_ASSISTANT_ID }}
        ASSISTANT_URL: "https://api.us-south.assistant.watson.cloud.ibm.com"
        DISCOVERY_APIKEY: ${{ secrets.D1_APIKEY }}
        DISCOVERY_ENVIRONMENT_ID: ${{ secrets.D1_ENVIRONMENT_ID }}
        DISCOVERY_COLLECTION_ID: ${{ secrets.D1_COLLECTION_ID }}
        DISCOVERY_URL: "https://api.us-south.discovery.watson.cloud.ibm.com"
        DISCOVERY_V2_APIKEY: ${{ secrets.D2_APIKEY }}
        DISCOVERY_V2_PROJECT_ID: ${{ secrets.D2_PROJECT_ID }}
        DISCOVERY_V2_COLLECTION_ID: ${{ secrets.D2_COLLECTION_ID }}
        DISCOVERY_V2_URL: "https://api.us-south.discovery.watson.cloud.ibm.com"
      run: |
        echo -e "\n\033[0;35mCommand: Run Integration Tests"
        dotnet test --no-build --verbosity normal src/IBM.Watson.LanguageTranslator.v3/Test/Integration
        dotnet test --no-build --verbosity normal src/IBM.Watson.NaturalLanguageUnderstanding.v1/Test/Integration
        dotnet test --no-build --verbosity normal src/IBM.Watson.SpeechToText.v1/Test/Integration
        dotnet test --no-build --verbosity normal src/IBM.Watson.TextToSpeech.v1/Test/Integration
        dotnet test --no-build --verbosity normal src/IBM.Watson.Assistant.v1/Test/Integration
        dotnet test --no-build --verbosity normal src/IBM.Watson.Assistant.v2/Test/Integration
        dotnet test --no-build --verbosity normal src/IBM.Watson.Discovery.v1/Test/Integration
        dotnet test --no-build --verbosity normal src/IBM.Watson.Discovery.v2/Test/Integration
        dotnet test --no-build --verbosity normal src/IBM.Watson.IntegrationTests

    # Do not notify on success.  We will leave the code here just in case we decide to switch gears
    - name: Notify slack on success
      if: false # success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: watson-e2e-tests
        status: SUCCESS
        color: good

    - name: Notify slack on failure
      if: false # failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: watson-e2e-tests
        status: FAILED
        color: danger
